### PR TITLE
Fixing the previous mistakes I did

### PR DESCRIPTION
**Pull request by clementFoyer**
My previous modifications to format actually did add some new mistakes. This PR should resolve that.

### CODE REVIEW

**Comment by trahay** [comment]
Hey Clément ! You've been granted write access to the repo, so you should be able to push your commit without needing an approval.

**Comment by clementFoyer** [comment]
Cheers François! I promise, I tested it before creating the PR :smile:

**Comment by clementFoyer** [comment]
It seems that I still can't push to master.

**Comment by trahay** [comment]
Is it working now ?

**Comment by clementFoyer** [comment]
Sorry I forgot to answer; yes, it should be working fine now.

**Pull request merged**
